const Report = require('../models/reportModel.js');

exports.fetchReports = async (req, res) => {
    try {
        const reports = await Report.find(getAll());
        res.status(200).json(reports);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
}

exports.fetchReportByUserId = async (req, res) => {
    try {
        const report = await Report.find(getReportByUserId(req.params.id));
        res.status(200).json(report);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
}

exports.fetchReportByPostId = async (req, res) => {
    try {
        const report = await Report.find(getReportByPostId(req.params.id));
        res.status(200).json(report);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
}

exports.createReport = async (req, res) => {
    const report = new Report({
        user_id: req.body.user_id,
        post_id: req.body.post_id,
        reason: req.body.reason
    });

    try {
        const newReport = await report.save();
        res.status(201).json(newReport);
    } catch (error) {
        res.status(400).json({ message: error.message });
    }
}

exports.updateReportById = async (req, res) => {
    try {
        const report = await Report.findById([req.params.user_id, req.params.post_id]);
        if (req.body.reason != null) {
            report.reason = req.body.reason;
        }
        const updatedReport = await report.save();
        res.status(200).json(report);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
}

exports.deleteReportById = async (req, res) => {
    try {
        const report = await Report.deleteReportById(req.params.user_id, req.params.post_id);
        res.status(200).json(report);
    } catch (error) {
        res.status(500).json({ message: error.message });
    }
}